usePodIdentity: "false"
keyvaultName: "{{KEYVAULT_NAME}}"
objects:  |
  array:
    - |
      objectName: "{{OBJECT1_NAME}}"
      objectAlias: "{{OBJECT1_ALIAS}}"
      objectType: "{{OBJECT1_TYPE}}"
      objectVersion: "{{OBJECT1_VERSION}}"
    - |
      objectName: "{{OBJECT2_NAME}}"
      objectAlias: "{{OBJECT2_ALIAS}}"
      objectType: "{{OBJECT2_TYPE}}"
      objectVersion: "{{OBJECT2_VERSION}}"
tenantId: "{{TENANT_ID}}"
